sync_config:
  access_token_secret_name: mage_git_access_token
  auth_type: https
  branch: main
  email: null
  remote_repo_link: https://github.com/Athreya-99/Mage-Sample.git
  repo_path: /home/src/mage_project
  ssh_private_key_secret_name: null
  ssh_public_key_secret_name: null
  sync_on_executor_start: null
  sync_on_pipeline_run: null
  sync_on_start: null
  sync_submodules: null
  type: null
  username: Athreya-99
